Repository alekseykondus/homepage, pull requests merged in 2021-05, with the labels that each got.

#3 First release to production
  README.md
  index.html
Labels: release

#8 Add base.css stylesheet link
  index.html
Labels: enhancement

#14 patch merge errors such as unexpecting "== and <<"
  index.html
Labels: bug, help wanted

#15 fix "<<<" bug
  index.html
Labels: bug, duplicate, help wanted
